services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: excelmind-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: excelmind_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - excelmind-network

  # Node.js Application
  app:
    build: .
    container_name: excelmind-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: excelmind_crm
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres123
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      JWT_EXPIRES_IN: 24h
    depends_on:
      - postgres
    networks:
      - excelmind-network
    volumes:
      - ./logs:/app/logs

  # pgAdmin - PostgreSQL Web Interface
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: excelmind-pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@excelmind.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - excelmind-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  excelmind-network:
    driver: bridge
